version: "3.3"

services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - kafkanet

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    ports:
      - 9600:9600
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - kafkanet

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
    networks:
      - kafkanet
    depends_on:
      - elasticsearch                                   # kibana will start when elasticsearch has started
networks:
    kafkanet:
        driver: bridge